from enum import Enum


class WorkOrderStatus(str, Enum):
    RECEIVED = "RECEIVED"
    IN_DIAGNOSIS = "IN_DIAGNOSIS"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    IN_REPAIR = "IN_REPAIR"
    ON_HOLD = "ON_HOLD"
    COMPLETED = "COMPLETED"
    DELIVERED = "DELIVERED"
